<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Redis;

class GeneralStock extends Model
{
    //
    protected $table = 'general_stocks';
    protected $primaryKey = 'id';
    public $incrementing = true;
    protected $fillable = ["id", "date", "general_start", "price_905", "today_final"];
    protected $hidden = ["created_at", "updated_at"];
    const UP = "1";
    const DOWN = "-1";

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
    }


}
