<?php

namespace App;

use App\Crawler\StockHelper;
use App\Jobs\Trading\BuyBack;
use App\Jobs\Trading\BuyBackParallel;
use App\Jobs\Trading\BuyBackStragedy2;
use App\Jobs\Trading\ShortSell0;
use App\Jobs\Trading\ShortSell1;
use App\Jobs\Update\UpdateDl;
use DateTime;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Redis;

class StockPrice extends Model
{
    protected $table = 'stock_prices';
    protected $primaryKey = 'id';
    protected $appends = ["current_time"];
    public $incrementing = true;
    public $timestamps = true;
    public $hidden = ["created_at", "updated_at", "trade_volume", "accumulate_trade_volume", "best_bid_volume", "best_ask_volume", "ps", "pz"];
    protected $casts = [
        'best_ask_price'  =>  'float',
        'best_bid_price'       =>  'float',
        'yesterday_final' => 'float',
        'high' => 'float',
        'low' => 'float',
        'latest_trade_price' => 'float'
    ];
    public $fillable = [
        "id",
        "code",
        "latest_trade_price",
        "trade_volume",
        "accumulate_trade_volume",
        "best_bid_price",
        "best_bid_volume",
        "best_ask_price",
        "best_ask_volume",
        "ps",
        "pz",
        "open",
        "high",
        "low",
        "yesterday_final",
        "date",
        "tlong",
        "created_at",
        "modified_at"
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::created(function (StockPrice $stockPrice){
            //Cache current stock info data to redis
            #Redis::del("Stock:realtime#{$stockPrice->code}");
            Redis::hmset("Stock:realtime#{$stockPrice->code}", $stockPrice->toArray());
            //Update dl data

            #return $stockPrice;

            /**
             * Determine trading type
             */

            if($stockPrice->current_price > 0){

                $dl0 = StockHelper::getDL0StocksCode($stockPrice->date);
                $dl1 = StockHelper::getDL1StocksCode($stockPrice->date);
                //Redis::rawCommand("lpos", "xtest", "12")

                //Sell DL0 between 09:00 and 12:30
                if($stockPrice->stock_time['hours'] < 12 || ($stockPrice->stock_time['hours'] == 12 && $stockPrice->stock_time['minutes'] <= 30)){

                    if(in_array($stockPrice->code, $dl0)){
                        ShortSell0::dispatchNow($stockPrice);
                    }
                }

                //Sell DL1 before 09:07am
                if($stockPrice->stock_time['hours'] == 9 && $stockPrice->stock_time['minutes'] <= 7){

                    if(in_array($stockPrice->code, $dl1)){
                        UpdateDl::dispatchNow($stockPrice);
                        ShortSell1::dispatchNow($stockPrice);
                    }
                }

                if($stockPrice->stock_time['hours'] >= 13){
                    BuyBackParallel::dispatchNow($stockPrice);
                }

            }




        });
    }

    /**
     * @return mixed
     */
    public function getCurrentPriceAttribute(){
        return $this->latest_trade_price > 0 ? $this->latest_trade_price : $this->best_ask_price;
    }

    /**
     * @return float|int
     */
    public function getCurrentPriceRangeAttribute(){
        return $this->yesterday_final > 0 ? (($this->current_price - $this->yesterday_final)/$this->yesterday_final)*100 : 0;
    }

    /**
     * @return array
     */
    public function getStockTimeAttribute(){
        return getdate($this->tlong / 1000);
    }

    /**
     * @return DateTime
     * @throws \Exception
     */
    public function getTimeAttribute(){
        $date = new DateTime();
        $date->setTimestamp($this->tlong/1000);
        return $date;
    }

    /**
     * @return String
     */
    public function getCurrentTimeAttribute(){
        return $this->time->format("H:i:s");
    }


}
