<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class StockOrder extends Model
{
    //
    protected $table = 'stock_orders';
    protected $primaryKey = 'id';
    public $incrementing = true;
    public $timestamps = true;
    public $fillable = [
        "id",
        "code",
        "qty",
        "price",
        "fee",
        "tax",
        "date",
        "tlong",
        "type",
        "deal_type",
        "created_at",
        "modified_at"
    ];



    const BUY = "1";
    const SELL = "0";
    const SHORT_SELL = "0";
    const BUY_LONG = "1";
    const DL1 = "1";
    const DL2 = "2";

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::created(function ($stock_order){
            Log::info("Order created {$stock_order->code}");
            $crawler = new Crawler\Crawler();

            $stock = Dl::where("code", $stock_order->code)->where("date", $stock_order->date)->first();
            if(!$stock){
                Log::debug("Stock not found on {$stock_order->date} {$stock_order->code}");
            }

            $limit_order = LimitOrder::where("date", $stock_order->date)->first();
            if(!$limit_order || ($limit_order->count == 0 && $limit_order->count < $limit_order->max)){

                if(!$limit_order){
                    $limit_order = new LimitOrder([
                        "date" => $stock_order->date
                    ]);
                }

                $limit_order->count ++;
                $limit_order->save();

                if($stock_order->type == self::BUY)
                    $crawler->buy($stock);

                else if($stock_order->type == self::SELL)
                    $crawler->sell($stock);
            }

        });

        /*static::saved(function ($stock_order){
            Log::info("Order saved {$stock_order->code}");
        });*/
    }



}
